name: rds-upgrade-paths

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 */3 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.0'

    - name: Install dependencies
      run: cd tools/rds-upgrade-paths/ && go get && go mod vendor

    - name: Execute
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: cd tools/rds-upgrade-paths/ && go run main.go

    - name: Commit & Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update RDS upgrade paths
        file_pattern: 'public/aws/rds-upgrade-paths/*.json'